
export const UNCHECKED_COMPNOPRESENT_NOTCONFIGURED = '0';
export const UNCHECKED_COMPPRESENT_NOTCONFIGURED = '1';
export const UNCHECKED_COMPPRESENT_ISCONFIGURED = '2';
export const UNCHECKED_COMPNOPRESENT_ISCONFIGURED = '3';

export const CHECKED_COMPNOPRESENT_NOTCONFIGURED = '4';
export const CHECKED_COMPPRESENT_NOTCONFIGURED = '5';
export const CHECKED_COMPPRESENT_ISCONFIGURED = '6';
export const CHECKED_COMPNOPRESENT_ISCONFIGURED = '7';
export const PARENT_NODE = '-1';







 